#include <QtTest>
#include <QFile>
#include <QTextStream>

#include "YearParser.h"

// Exercises normalizeYear() against the rogue date/year formats found in real
// tags. Run with: ctest --test-dir build  (or ./build/year_test)
//
// Two layers:
//   normalizes  — hand-written cases covering boundaries that may not appear in
//                 any given library (empty, out-of-range, two-digit, junk).
//   golden      — a data-driven characterisation case over tests/year_cases.tsv,
//                 a deduped/shape-bucketed sample of real tags generated by
//                 scripts/build_year_cases.py with expectations pre-filled by the
//                 parser itself. Skipped when the fixture is absent. It locks in
//                 current behaviour, so a parser change that shifts any real-world
//                 input shows up here for review.
class YearParserTest : public QObject
{
    Q_OBJECT
private slots:
    void normalizes_data();
    void normalizes();
    void golden_data();
    void golden();
};

void YearParserTest::normalizes_data()
{
    QTest::addColumn<QString>("raw");
    QTest::addColumn<int>("expected");

    // Plain years
    QTest::newRow("plain")            << "2007"                  << 2007;
    QTest::newRow("whitespace")       << "  1985  "             << 1985;

    // Dates with separators
    QTest::newRow("iso-date")         << "2007-05-01"            << 2007;
    QTest::newRow("iso-timestamp")    << "1985-03-12T00:00:00Z"  << 1985;
    QTest::newRow("slash-ymd")        << "2007/05/01"            << 2007;
    QTest::newRow("dot-ym")           << "2007.05"               << 2007;
    QTest::newRow("month-first")      << "05/2007"               << 2007;

    // Words around the year
    QTest::newRow("month-name")       << "May 2007"              << 2007;
    QTest::newRow("remaster-suffix")  << "1999 (Remastered)"     << 1999;

    // Ranges -> first plausible
    QTest::newRow("range")            << "2007-2009"             << 2007;

    // Compact YYYYMMDD
    QTest::newRow("yyyymmdd")         << "20070501"              << 2007;

    // Unknown / junk -> 0
    QTest::newRow("empty")            << ""                      << 0;
    QTest::newRow("whitespace-only")  << "   "                  << 0;
    QTest::newRow("zeros")            << "0000"                  << 0;
    QTest::newRow("two-digit")        << "07"                    << 0;
    QTest::newRow("text")             << "Unknown"               << 0;
    QTest::newRow("partial-decade")   << "199x"                  << 0;

    // Implausible numbers -> 0
    QTest::newRow("too-old")          << "1234"                  << 0;
    QTest::newRow("far-future")       << "3001"                  << 0;
    QTest::newRow("catalogue-id")     << "12345"                 << 0;
}

void YearParserTest::normalizes()
{
    QFETCH(QString, raw);
    QFETCH(int, expected);
    QCOMPARE(normalizeYear(raw), expected);
}

void YearParserTest::golden_data()
{
    QTest::addColumn<QString>("raw");
    QTest::addColumn<int>("expected");

#ifndef YEAR_CASES_FILE
    QSKIP("No fixture path configured (YEAR_CASES_FILE undefined).");
#else
    QFile f(QStringLiteral(YEAR_CASES_FILE));
    if (!f.exists())
        QSKIP("No fixture; generate it with scripts/build_year_cases.py.");
    QVERIFY2(f.open(QIODevice::ReadOnly | QIODevice::Text), "fixture unreadable");

    // Tab-separated: raw \t expected [\t shape \t count]. '#' lines are comments.
    // raw is the literal tag value, so it may be empty or hold leading/trailing
    // spaces — only split on the first tab and never trim the raw column.
    QTextStream in(&f);
    int n = 0;
    while (!in.atEnd()) {
        const QString line = in.readLine();
        if (line.startsWith('#'))
            continue;
        const int tab = line.indexOf('\t');
        if (tab < 0)
            continue;
        const QString raw = line.left(tab);
        const QString rest = line.mid(tab + 1);
        const int expected = rest.left(rest.indexOf('\t') < 0 ? rest.size()
                                                              : rest.indexOf('\t')).toInt();
        QTest::addRow("case-%d", n++) << raw << expected;
    }
    if (n == 0)
        QSKIP("Fixture present but held no cases.");
#endif
}

void YearParserTest::golden()
{
    QFETCH(QString, raw);
    QFETCH(int, expected);
    QCOMPARE(normalizeYear(raw), expected);
}

QTEST_APPLESS_MAIN(YearParserTest)
#include "YearParserTest.moc"
